# Generated by Django 3.1.1 on 2022-04-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('book_pages', models.IntegerField()),
                ('publish_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
